Repository 12-Cookie/cookie-s, pull requests merged in 2023-10, with the labels that each got.

#5 공통 css변경, 공통 컴포넌트 NameBadge 추가
  src/App.css
  src/App.jsx
  src/components/common/NameBadge/NameBadge.jsx
  src/components/common/NameBadge/NameBadge.style.jsx
Labels: feat

#9 Feat: 직원 로그인 페이지 구현
  src/pages/Dashboard/staff/Dashboard_S.jsx
  src/pages/Login/Login.jsx
Labels: feat

#10 theme파일 추가 및 역할배정 페이지 header 레이아웃
  src/components/Schedule/admin/assignRole/AssignHeader.jsx
  src/components/Schedule/admin/assignRole/AssignHeader.style.jsx
  src/components/common/NameBadge/NameBadge.jsx
  src/components/common/NameBadge/NameBadge.style.jsx
  src/main.jsx
  src/pages/Schedule/admin/assignRole/AssignRole.jsx
  src/theme/index.js
  src/utils/amOrPm.js
  src/utils/getDayOfWeek.js
Labels: feat

#11 useFireFetch()수정, chakra ui Tag 컴포넌트 테마 변경
  src/components/Schedule/admin/assignRole/AssignBody/AssignBody.jsx
  src/components/Schedule/admin/assignRole/AssignBody/AssignBody.style.jsx
  src/components/Schedule/admin/assignRole/AssignFooter/AssignFooter.jsx
  src/components/Schedule/admin/assignRole/AssignFooter/AssignFooter.style.jsx
  src/components/Schedule/admin/assignRole/AssignHeader/AssignHeader.jsx
  src/components/Schedule/admin/assignRole/AssignHeader/AssignHeader.style.jsx
  src/hooks/useFireFetch.jsx
  src/pages/Schedule/admin/assignRole/AssignRole.jsx
  src/theme/index.js
Labels: feat

#13 관리자 로그인 페이지 구현
  package-lock.json
  package.json
  src/pages/Login/admin/login/LoginForm.jsx
  src/pages/Login/admin/login/Login_A.jsx
Labels: feat

#15 역할 배정 페이지 기본적인 기능 완료
  src/components/Schedule/admin/assignRole/AssignBody/AssignBody.jsx
  src/components/Schedule/admin/assignRole/AssignBody/AssignBody.style.jsx
  src/components/Schedule/admin/assignRole/AssignFooter/AssignFooter.jsx
  src/pages/Schedule/admin/assignRole/AssignRole.jsx
  src/theme/index.js
Labels: feat

#17 1 week
  .gitignore
  .prettierrc
  README.md
  package-lock.json
  package.json
  src/App.css
  src/App.jsx
  src/components/Schedule/admin/assignRole/AssignBody/AssignBody.jsx
  src/components/Schedule/admin/assignRole/AssignBody/AssignBody.style.jsx
  src/components/Schedule/admin/assignRole/AssignFooter/AssignFooter.jsx
  src/components/Schedule/admin/assignRole/AssignFooter/AssignFooter.style.jsx
  src/components/Schedule/admin/assignRole/AssignHeader/AssignHeader.jsx
  src/components/Schedule/admin/assignRole/AssignHeader/AssignHeader.style.jsx
  src/components/StaffManagement/StaffManagement.jsx
  src/components/StaffManagement/StaffManagement.style.jsx
  src/components/common/NoticeItem/NoticeItem.jsx
  src/components/common/NoticeItem/NoticeItem.style.jsx
  src/components/common/ScheduleItem/ScheduleItem.jsx
  src/components/common/ScheduleItem/ScheduleItem.style.jsx
  src/components/common/ScheduleRoleItem/ScheduleRoleItem.jsx
  src/components/common/ScheduleUtilItem/ScheduleUtilItem.jsx
  src/components/common/ScheduleUtilItem/ScheduleUtilItem.style.jsx
  src/hooks/useFireFetch.jsx
  src/main.jsx
  src/pages/Dashboard/admin/Dashboard_A.jsx
  src/pages/Dashboard/admin/notice/Notice.jsx
  src/pages/Dashboard/admin/notice/Notice.style.jsx
  src/pages/Dashboard/staff/Dashboard_S.jsx
  src/pages/Dashboard/staff/Dashboard_S.style.jsx
  src/pages/Login/Login.jsx
  src/pages/Login/admin/login/LoginForm.jsx
  src/pages/Login/admin/login/Login_A.jsx
  src/pages/Schedule/admin/assignRole/AssignRole.jsx
  src/theme/index.js
  src/utils/amOrPm.js
  src/utils/getDayOfWeek.js
Labels: deploy

#18 파이어베이스 수정, 어드민계정 페이지 추가
  src/App.jsx
  src/components/common/BottomNav/BottomNav.jsx
  src/components/icons/Company_i.jsx
  src/firebase/firebase.js
  src/hooks/useFireFetch.jsx
  src/pages/Workers/Workers.jsx
  src/pages/Workers/Workers.style.jsx
Labels: feat

#22 유저 정보 입력, 핀번호 입력 페이지 구현
  src/components/Login/LoginForm.jsx
  src/pages/Login/Login.jsx
  src/pages/Login/admin/infoForm/InfoForm_A.jsx
  src/pages/Login/admin/login/Login_A.jsx
  src/pages/Login/staff/SubmitCode/SubmitCode.jsx
  src/pages/Login/staff/infoForm/InfoForm_S.jsx
  src/utils/combineArrayToNumber.js
Labels: feat

#21 Design: ScheduleUtipWrap button -> div change
  src/components/common/ScheduleUtilItem/ScheduleUtilItem.style.jsx
  src/pages/Dashboard/staff/Dashboard_S.jsx
Labels: HTML&CSS

#23 데이터 삭제기능 추가, 스케줄 아이템 코드 변경
  src/components/Schedule/admin/assignRole/AssignBody/AssignBody.jsx
  src/components/Schedule/admin/assignRole/AssignFooter/AssignFooter.jsx
  src/components/common/ScheduleItem/ScheduleItem.jsx
  src/components/common/ScheduleUtilItem/ScheduleUtilItem.jsx
  src/components/common/ScheduleUtilItem/ScheduleUtilItem.style.jsx
  src/hooks/useFireFetch.jsx
  src/pages/Schedule/admin/assignRole/AssignRole.jsx
  src/pages/Schedule/admin/manageSchedule/ManageSchedule_A.jsx
Labels: feat

#25 zustand 설치
  package-lock.json
  package.json
Labels: feat

#26 Style: 로그인 페이지 스타일링
  src/components/Login/LoginForm.jsx
  src/pages/Login/Login.jsx
  src/pages/Login/Login.style.jsx
  src/pages/Login/admin/infoForm/InfoForm_A.jsx
  src/pages/Login/admin/infoForm/InfoForm_A.style.jsx
  src/pages/Login/admin/login/Login_A.jsx
  src/pages/Login/admin/login/Login_A.style.jsx
  src/pages/Login/staff/SubmitCode/SubmitCode.jsx
  src/pages/Login/staff/SubmitCode/SubmitCode.style.jsx
  src/pages/Login/staff/infoForm/InfoForm_S.jsx
  src/pages/Login/staff/infoForm/InfoForm_S.style.jsx
Labels: HTML&CSS

#29 Feat: 로그인 상태관리 기능 추가 및 user 정보 db에 저장
  package-lock.json
  package.json
  src/App.jsx
  src/components/Login/LoginForm.jsx
  src/pages/Dashboard/staff/Dashboard_S.jsx
  src/pages/Login/Login.jsx
  src/pages/Login/admin/infoForm/InfoForm_A.jsx
  src/pages/Login/admin/login/Login_A.jsx
  src/pages/Login/staff/SubmitCode/SubmitCode.jsx
  src/pages/Login/staff/infoForm/InfoForm_S.jsx
  src/store/company/useCompanyStore.js
  src/store/user/useUserStore.js
Labels: feat

#31 typo fix, sheduleItem 상태 분기처리
  src/components/Schedule/admin/assignRole/AssignBody/AssignBody.jsx
  src/components/common/ScheduleItem/ScheduleItem.jsx
Labels: bug

#33 Feat: localStorage활용하여 로그인 여부 확인
  src/pages/Login/Login.jsx
  src/pages/Login/admin/infoForm/InfoForm_A.jsx
  src/pages/Login/admin/login/Login_A.jsx
  src/store/user/useUserStore.js
Labels: feat

#37 Bug: 로그인시 FireBaseError 수정
  src/App.jsx
  src/pages/Dashboard/staff/Dashboard_S.jsx
  src/pages/Info/admin/Info_A.jsx
  src/pages/Info/staff/Info_S.jsx
  src/pages/Login/Login.jsx
  src/pages/Login/admin/login/Login_A.jsx
  src/store/company/useCompanyStore.js
  src/store/user/useUserStore.js
Labels: bug

#38 스케줄 관리, 역할 배정 페이지 기본 기능 완료, 파이어베이스 업데이트 기능 추가
  src/App.jsx
  src/components/Schedule/admin/assignRole/AssignFooter/AssignFooter.jsx
  src/components/common/ScheduleItem/ScheduleItem.jsx
  src/components/common/ScheduleRoleItem/ScheduleRoleItem.jsx
  src/components/common/ScheduleUtilItem/ScheduleUtilItem.jsx
  src/hooks/useFireFetch.jsx
  src/pages/Dashboard/admin/Dashboard_A.jsx
  src/pages/Schedule/admin/assignRole/AssignRole.jsx
  src/pages/Schedule/admin/manageSchedule/ManageSchedule_A.jsx
  src/pages/Schedule/staff/manageSchedule/ManageSchedule_S.jsx
  src/store/company/useCompanyStore.js
Labels: feat

#40 로그인 회사코드 입력 비동기 처리, scheduleRoleItem optional chaining 추가
  src/components/common/ScheduleRoleItem/ScheduleRoleItem.jsx
  src/hooks/useFireFetch.jsx
  src/pages/Login/staff/SubmitCode/SubmitCode.jsx
  src/pages/Login/staff/infoForm/InfoForm_S.jsx
Labels: bug, feat
