Repository 12-Cookie/cookie-s, pull requests merged in 2023-11, with the labels that each got.

#44 역할배정 완료 시 버튼 비활성화
  src/components/common/ScheduleItem/ScheduleItem.jsx
  src/components/common/ScheduleUtilItem/ScheduleUtilItem.jsx
  src/pages/Schedule/admin/assignRole/AssignRole.jsx
Labels: feat

#47 scheduleItem props 문제 해결, 스케줄 관리 직원 페이지 로딩 추가
  src/pages/Schedule/staff/manageSchedule/ManageSchedule_S.jsx
Labels: bug, feat

#52 Update README.md
  README.md
Labels: documentation

#54 Bug: ScheduleItem 데이터 받아올 때 서로 다른 데이터 참조하는 이슈 #50
  src/components/common/ScheduleItem/ScheduleItem.jsx
  src/pages/Dashboard/staff/Dashboard_S.jsx
Labels: bug

#51 Bug: SubmitCode 페이지 오류 수정
  src/pages/Login/staff/SubmitCode/SubmitCode.jsx
Labels: bug

#56 Update README.md
  README.md
Labels: documentation

#57 로고 변경, vite 설정
  index.html
  package-lock.json
  package.json
  public/logo.png
  public/vite.svg
  vite.config.js
Labels: feat

#61 Doc: 오타 수정 및 console.log 삭제
  README.md
  index.html
  src/components/Schedule/admin/assignRole/AssignFooter/AssignFooter.jsx
  src/components/Schedule/staff/UserApplyItem.jsx
  src/components/StaffManagement/StaffManagement.jsx
  src/components/common/ScheduleUtilItem/ScheduleUtilItem.jsx
  src/pages/Dashboard/admin/Dashboard_A.jsx
  src/pages/Dashboard/staff/Dashboard_S.jsx
  src/pages/Dashboard/staff/NoData.jsx
Labels: documentation

#59 배포 404 오류 수정 (설정파일 추가)
  vercel.json
Labels: bug, feat

#64 공지사항 슬라이드 드래그 클릭 삭제 후 공지사항 페이지로 이동하기 기능 구현
  src/components/StaffManagement/StaffManagement.jsx
  src/pages/Dashboard/admin/notice/Notice.jsx
Labels: feat

#67 Bug: InfoForm post시 전달되는 데이터 형식 수정
  src/pages/Login/Login.jsx
  src/pages/Login/admin/infoForm/InfoForm_A.jsx
  src/pages/Login/admin/login/Login_A.jsx
  src/pages/Login/staff/infoForm/InfoForm_S.jsx
Labels: bug

#73 Feat: 관리자 계정 생성 시 companyId 자동 등록
  src/pages/Login/admin/infoForm/InfoForm_A.jsx
  src/pages/Salary/Salary_S.jsx
  src/pages/Workers/Workers.jsx
Labels: feat

#74 deploy
  README.md
  index.html
  src/components/Dashboard/NoData.jsx
  src/components/Dashboard/NoData.style.jsx
  src/components/Schedule/admin/assignRole/AssignFooter/AssignFooter.jsx
  src/components/Schedule/staff/UserApplyItem.jsx
  src/components/StaffManagement/StaffManagement.jsx
  src/components/common/ScheduleItem/ScheduleItem.jsx
  src/components/common/ScheduleUtilItem/ScheduleUtilItem.jsx
  src/pages/Dashboard/admin/Dashboard_A.jsx
  src/pages/Dashboard/admin/notice/Notice.jsx
  src/pages/Dashboard/staff/Dashboard_S.jsx
  src/pages/Dashboard/staff/chart/Chart.jsx
  src/pages/Info/admin/Info_A.jsx
  src/pages/Info/staff/Info_S.jsx
  src/pages/Login/Login.jsx
  src/pages/Login/admin/infoForm/InfoForm_A.jsx
  src/pages/Login/admin/login/Login_A.jsx
  src/pages/Login/staff/infoForm/InfoForm_S.jsx
  src/pages/Notice/admin/AddNotice/AddNotice.jsx
  src/pages/Notice/admin/Notice_A.jsx
  src/pages/Notice/staff/Notice_S.jsx
  src/pages/Salary/SalaryCalendar.jsx
  src/pages/Salary/Salary_S.jsx
  src/pages/Salary/Salary_S.style.jsx
  src/pages/Workers/Workers.jsx
  src/pages/Workers/Workers.style.jsx
  src/utils/legalAge.js
  vercel.json
Labels: deploy
